version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://testuser:123123@postgres:5432/test_kraud
      NODE_ENV: development
      PORT: 3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - postgres
    env_file:
    - .env
    ports:
      - "3001:3001"
    # Run a command against the development stage of the image
    command: yarn start
    
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"